### ISSUE TITLE
Error: This version of ChromeDriver only supports Chrome version 83

### ISSUE THREAD

**Issue by pmill** [zaherg/laravel-dusk#2]
Hello

I'm getting the following error when running on Bitbucket Pipelines, can you help?

```
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 83
/opt/atlassian/pipelines/agent/build/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:125
/opt/atlassian/pipelines/agent/build/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:370
/opt/atlassian/pipelines/agent/build/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:136
/opt/atlassian/pipelines/agent/build/tests/DuskTestCase.php:42
/opt/atlassian/pipelines/agent/build/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:200
/opt/atlassian/pipelines/agent/build/vendor/laravel/framework/src/Illuminate/Support/helpers.php:393
/opt/atlassian/pipelines/agent/build/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:201
/opt/atlassian/pipelines/agent/build/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:95
/opt/atlassian/pipelines/agent/build/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:65
```

Our pipeline step is:

```
      - step:
          name: run-tests
          image: zaherg/laravel-dusk:7.3
          script:
            - cp .env.dusk.local .env
            - php artisan config:clear
            - php artisan config:cache
            - php artisan dusk:chrome-driver
            - php artisan dusk
```

The output from `php artisan dusk:chrome-driver` is "ChromeDriver binary successfully installed for version 83.0.4103.39.".

Any help would be much appreciated.

Thanks

Peter
